### ISSUE TITLE
Problem when doing "$this->ztbForm($form);" in view

### ISSUE THREAD

**Issue by jeffchulg** [mwillbanks/ZfcTwitterBootstrap#11]
Hi ! 
First of all thank you for this module, it seems to be cool. 
I'm experiencing a little problem when rendering my form :
[Mon Nov 19 09:25:51 2012] [error] [client XXX] PHP Fatal error:  Uncaught exception 'Zend\View\Exception\InvalidArgumentException' with message 'Object provided to Escape helper, but flags do not allow recursion' in /home/jeff/projects/winyumweb/zf2/vendor/zendframework/zendframework/library/Zend/View/Helper/Escaper/AbstractHelper.php:118\nStack trace:\n#0 /home/jeff/projects/winyumweb/zf2/vendor/zendframework/zendframework/library/Zend/Form/View/Helper/AbstractHelper.php(233): Zend\View\Helper\Escaper\AbstractHelper->__invoke(Object(Zend\Mvc\Controller\Plugin\Url))\n#1 /home/jeff/projects/winyumweb/zf2/vendor/zendframework/zendframework/library/Zend/Form/View/Helper/Form.php(71): Zend\Form\View\Helper\AbstractHelper->createAttributesString(Array)\n#2 /home/jeff/projects/winyumweb/zf2/vendor/ZfcTwitterBootstrap/src/ZfcTwitterBootstrap/Form/View/Helper/Form.php(98): Zend\Form\View\Helper\Form->openTag(Object(Zend\Form\Form))\n#3 [internal function]: ZfcTwitterBootstrap\Form\View\Helper\Form->__invoke(Object(Zend\Form\Form))\n#4 /home/jeff/projects/winyumweb/zf2/vendor/zendframewo in /home/jeff/projects/winyumweb/zf2/vendor/zendframework/zendframework/library/Zend/View/Helper/Escaper/AbstractHelper.php on line 118, referer: http://XXX/zf2/public/winyum

Can you help me on that ??

**Comment by mwillbanks** [comment]
Could you let me know what you are passing into that form?  It seems like there is some form of recursion based off of the exception.

**Comment by jeffchulg** [comment]
Here is the code that generates the form which lead to this error : 

```
protected function getDeployForm() {
    if(!$this->_deployform) {
        $this->_deployform = new Form('FORM_deploy') ;

        // attributs
        $this->_deployform->setAttribute('action', $this->url('winyum/deploy'));
        $this->_deployform->setAttribute('method', 'post');

        // ajout des champs
        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Select',
            'name' => 'cliapp',
            'attributes' =>  array(
                'id' => 'cliapp',
            ),
            'options' => array(
                'label' => 'Dépôt:',
                'required' => true,
            ),
        ));

        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Radio',
            'name' => 'opt1' ,
            'attributes' => array(
                'value' => 'nothing',
            ),
            'options' => array(
                'label' => 'Travail prealable sur les fichiers déjà présents?',
                'required' => true,
                'value_options' => array(
                    'nothing' => 'Ne rien faire',
                    'deleteall' => 'Effacer tout dans le répertoire de base',
                    'deletefilesonly' => 'Effacer les fichiers/répertoires listés ci-dessous',
                ),
            ),
        ));

        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Text',
            'name' => 'opt2' ,
            'attributes' => array(
                'value' => '*.*',
            ),
            'options' => array(
                'label' => 'Fichiers pour travail préalable',
                'required' => true,
            ),
        ));

        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Radio',
            'name' => 'opt3' ,
            'attributes' => array(
                'value' => '2',
            ),
            'options' => array(
                'label' => 'Forcer la prochaine mise à jour des clients à:',
                'required' => true,
                'value_options' => array(
                    '1' => 'Niveau 1 (pas de vérification)',
                    '2' => 'Niveau 2 (Comparaison à priori - non MD5)',
                    '3' => 'Niveau 3 (Calcul MD5 et comparaison',
                ),
            ),
        ));

        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Radio',
            'name' => 'opt4' ,
            'attributes' => array(
                'value' => '2',
            ),
            'options' => array(
                'label' => 'Définir le niveau de mise à jour par défaut des clients à:',
                'required' => true,
                'value_options' => array(
                    '1' => 'Niveau 1 (Pas de vérifications)',
                    '2' => 'Niveau 2 (Comparaison à priori - non MD5)',
                    '3' => 'Niveau 3 (Calcul MD5 et comparaison',
                ),
            ),
        ));

        $this->_deployform->add(array(
            'name' => 'fileupload',
            'attributes' => array(
                'type'  => 'file',
            ),
            'options' => array(
                'label' => 'Fichier ZIP à charger:',
                'required' => true,
            ),
        ));

        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Textarea',
            'name' => 'comment2',
            'options' => array(
                'label' => 'Commentaire:',
                'required' => false,
            ),
        ));

        $this->_deployform->add(array(
            'type' => 'Zend\Form\Element\Csrf',
            'name' => 'security',
        ));

        $this->_deployform->add(array(
            'name' => 'submit',
            'attributes' => array(
                'type'  => 'submit',
                'value' => 'Changer le niveau',
                'id' => 'submitbutton',
            ),
        ));

    }

    return $this->_deployform ;
}
```

**Comment by jeffchulg** [comment]
I found the problem : it was because of "this->url('....')"

By the way, is there a way to get a horizontal form ?

**Comment by mwillbanks** [comment]
You should just be able to add the class to the form itself:
$this->setAttribute('class', 'form-horizontal');
